apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-gpu-monitoring-daemonset
  labels:
    k8s-app: nvidia-gpu-monitoring-daemonset
spec:
  selector:
    matchLabels:
      k8s-app: nvidia-gpu-monitoring-daemonset
  template:
    metadata:
      labels:
        k8s-app: nvidia-gpu-monitoring-daemonset
    spec:
      containers:
      - image: "gcr.io/dashpole-kubernetes-test/gpu-monitor:v2"
        name: gpu-monitor
        args: ["--socket=/podresources/kubelet.sock", --v=10]
        volumeMounts:
        - name: kubelet-podresources
          mountPath: /podresources
        - name: dev
          mountPath: /dev
        - name: libnvidia
          mountPath: /home/kubernetes/bin/nvidia/lib64/
        securityContext:
          privileged: true
        env:
        - name: LD_LIBRARY_PATH
          value: "/home/kubernetes/bin/nvidia/lib64/"
      volumes:
        - name: kubelet-podresources
          hostPath:
            path: /var/lib/kubelet/
        - name: dev
          hostPath:
            path: /dev
        - name: libnvidia
          hostPath:
            path: /home/kubernetes/bin/nvidia/lib64/
